### ISSUE TITLE
How to insert Int64 data type into mongo ?

### ISSUE THREAD

**Issue by HamzaKhait** [neoxic/lua-mongo#10]
Hello,

When I insert an Integer into mongoDB it's displayed as Int32.
Could someone please tell me how to add the field **startDate** as Int64 ?

```
local myCollection = client:getCollection('testDB', 'conferences')

local conference = {
   name = "test",
   numberOfParticipants = 0,
   startDate = os.time()
};

myCollection:insert(json.encode(conference))
```

Thanks for your help!

**Comment by neoxic** [comment]
Take a look into the `test/` folder. You can find many useful examples there of how to work with this libarary. Come back if still lost.

**Comment by HamzaKhait** [comment]
Hi,

Thanks for your response, I solved my issue with the following modification : 

```
local conference = {
   name = "test",
   numberOfParticipants = 0,
   startDate = { ["$numberLong"] = tostring(os.time()) }
};
```
I am not sure it's the perfect solution but it works well.
You can close this issue.

**Comment by neoxic** [comment]
```Lua
local conference = {
   name = "test",
   numberOfParticipants = 0,
   startDate = mongo.Int64(os.time()),
}
```
Looks much better, eh?
