### ISSUE TITLE
client connection error handling

### ISSUE THREAD

**Issue by byoungdale** [neoxic/lua-mongo#11]
Is there a way to find out if and/or why the mongo client connection failed? I see that when I do a mongo.Client() call, I get a return value even if the connection to the database failed. Even if I put it a incorrect URI, I still get a client connection value returned, but it does not work and at the same time there are no errors.

```lua
local uri = 'mongodb://1274.8398.433.344' -- or correct but inaccessible database URI
local client = mongo.Client()
local collection = client:getCollection('mail', 'data')

  collection:insert{
      key = value
  }
```

This will run fine with no errors even though `uri` is not correct or if for some reason connection to the URI fails. Is there any way to get an error back?

**Comment by neoxic** [comment]
How about that?
```Lua
assert(collection:insert{ key = value })
```
Most functions return `nil` and the error message in case of errors. Please refer to the docs.
