### ISSUE TITLE
How to insert document with ISODate object

### ISSUE THREAD

**Issue by sergeydi** [neoxic/lua-mongo#16]
Hi,
How to do something like:

```
db.log_events.insert( {
   "createdAt": new Date(),
   "logEvent": 2,
   "logMessage": "Success!"
} )
```

**Comment by neoxic** [comment]
```Lua
collection:insert{
    createdAt = mongo.DateTime(os.time()),
    logEvent = 2,
    logMessage = 'Success!',
}
```
Eh?

**Comment by neoxic** [comment]
I encourage you to first read the API Reference and then, if still uncertain, take a look at the BSON testing suite under `test/`.

https://github.com/neoxic/lua-mongo/blob/master/doc/main.md

**Comment by sergeydi** [comment]
Thank you.
The working solution:
`createdAt = mongo.DateTime(os.time() * 1000)`

**Comment by neoxic** [comment]
Right, the timestamp is in milliseconds.
