### ISSUE TITLE
I have problem with luarocks install lua-mongo.

### ISSUE THREAD

**Issue by tomanupong** [neoxic/lua-mongo#17]
**I have problem with luarocks install lua-mongo.**
I install luarocks install lua-mongo. Have problem. help me please. thank you.
**I've already installed bson lib.**
-----------------------
Installing https://luarocks.org/lua-mongo-1.2.1-1.src.rock

Error: Could not find header file for LIBBSON
  No file libbson-1.0/bson/bson.h in /usr/local/include
  No file libbson-1.0/bson/bson.h in /usr/include
You may have to install LIBBSON in your system and/or pass LIBBSON_DIR or LIBBSON_INCDIR to the luarocks command.
Example: luarocks install lua-mongo LIBBSON_DIR=/usr/local

**Comment by neoxic** [comment]
You need an installed `mongo-c-driver` package in your system in order to build `lua-mongo`. It appears your `libbson` (which is just one of two parts of Mongo C Driver) is not installed into the default prefix. Try to find its header with:
```
find / -name 'bson.h'
```
and go from there.

**Comment by tomanupong** [comment]
i try command line.
`find / -name 'bson.h'`
answer:
```
/home/tom/Downloads/libbson-1.9.3/src/bson/bson.h
/home/tom/Downloads/mongo-c-driver-1.9.3/src/libbson/src/bson/bson.h
/usr/local/include/libbson-1.0/bson.h
/usr/include/libbson-1.0/bson/bson.h
/usr/include/libbson-1.0/bson.h
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
```

thank you . I try from Sergeydi.
```
$ git clone https://github.com/mongodb/mongo-c-driver.git
$ cd mongo-c-driver
$ python build/calc_release_version.py > VERSION_CURRENT
$ mkdir cmake-build
$ cd cmake-build
$ cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
$ make
$ sudo make install
```
It's works thank you verymuch guy.

**Comment by GitHubProgarm** [comment]
> ## **I have problem with luarocks install lua-mongo.**
> I install luarocks install lua-mongo. Have problem. help me please. thank you.
> **I've already installed bson lib.**
> Installing https://luarocks.org/lua-mongo-1.2.1-1.src.rock
> 
> Error: Could not find header file for LIBBSON
> No file libbson-1.0/bson/bson.h in /usr/local/include
> No file libbson-1.0/bson/bson.h in /usr/include
> You may have to install LIBBSON in your system and/or pass LIBBSON_DIR or LIBBSON_INCDIR to the luarocks command.
> Example: luarocks install lua-mongo LIBBSON_DIR=/usr/local

you can build mongo.so with luarocks???
