### ISSUE TITLE
I builde lua-mongo success, But there is something wrong with the use

### ISSUE THREAD

**Issue by GitHubProgarm** [neoxic/lua-mongo#18]
build  mongo-c-driver 1.15 with luarock
-rwxr-xr-x 1 root root 93680 Nov  1 11:01 mongo.so
drwxr-xr-x 2 root root    53 Mar 27  2019 socket
[root@centos01 5.3]# ldd mongo.so
        linux-vdso.so.1 =>  (0x00007ffc6fbec000)
        libmongoc-1.0.so.0 => not found
        libbson-1.0.so.0 => /usr/local/lib/libbson-1.0.so.0 (0x00007f0fbcc30000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0fbc86d000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f0fbc56b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0fbc34e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0fbd082000)

problem is 
error : ...ect/LinuxLua/AgentServer/build/lua/5.3/include/mongo.lua:1: module 'bson' not found:
        no field package.preload['bson']
        no file './lua/bson.lua'
        no file '/usr/local/share/lua/5.3/bson.lua'
        no file '/usr/local/share/lua/5.3/bson/init.lua'
        no file '/usr/local/lib/lua/5.3/bson.lua'
        no file '/usr/local/lib/lua/5.3/bson/init.lua'
        no file './bson.lua'
        no file './bson/init.luabson.lua'
        no file '/data/project/LinuxLua/AgentServer/build/lua/5.3/include/bson.lua'
        no file '/usr/local/lib/lua/5.3/bson.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './bson.sobson.so'
        no file '/data/project/LinuxLua/AgentServer/build/lua/5.3/lib/bson.so'
        stack[0] -> line -1 : unknown[[C] : line -1]
        stack[1] -> line -1 : require()[[C] : line -1]
        stack[2] -> line 1 : unknown[...ect/LinuxLua/AgentServer/build/lua/5.3/include/mongo.lua : line 0]
        stack[3] -> line -1 : require()[[C] : line -1]
        stack[4] -> line 78 : unknown[./lua/testmongo.lua : line 0]
        stack[5] -> line -1 : require()[[C] : line -1]
        stack[6] -> line 146 : unknown[lua/ManagerTest.lua : line 0]

I build and use in window is ok ,but linux is wrong!! why??
filename diffance?

**Comment by neoxic** [comment]
```
error : ...ect/LinuxLua/AgentServer/build/lua/5.3/include/mongo.lua:1: module 'bson' not found
```
How is this related to `lua-mongo`?

**Comment by neoxic** [comment]
Looks like you are doing ...
```Lua
require 'bson'
```
... in your code.

To use `lua-mongo`, one must do:
```Lua
require 'mongo'
```
See README for more info.

**Comment by GitHubProgarm** [comment]
use on win like this 
local mongo = require 'mongo'
local client = mongo.Client(test.uri)

**Comment by moteus** [comment]
May   be your code uses different mongo module?

**Comment by GitHubProgarm** [comment]
no! I build mongo-c-drivar user for C++ no problem , now i use luarocks exprot lua-mongo (mongo.so) is wrong ?  I dont think so , i think lua-mongo-1.2.1-1.rockspec problem here

build = {
	type = 'builtin',
	modules = {
		mongo = {
			sources = {
				'src/bson.c',
				'src/bsontype.c',
				'src/bulkoperation.c',
				'src/client.c',
				'src/collection.c',
				'src/cursor.c',
				'src/database.c',
				'src/flags.c',
				'src/gridfs.c',
				'src/gridfsfile.c',
				'src/gridfsfilelist.c',
				'src/main.c',
				'src/objectid.c',
				'src/readprefs.c',
				'src/util.c',
			},
			libraries = {'mongoc-1.0', 'bson-1.0'},
			incdirs = {'$(LIBMONGOC_INCDIR)/libmongoc-1.0', '$(LIBBSON_INCDIR)/libbson-1.0'},
			libdirs = {'$(LIBMONGOC_LIBDIR)', '$(LIBBSON_LIBDIR)'},
		},
	},
}

**Comment by GitHubProgarm** [comment]
you project is suppor tmongo-c-driver 1.15?

**Comment by moteus** [comment]
Where you get `mongo.lua` file 
It is not a part of this `lua-mongo` module.

**Comment by GitHubProgarm** [comment]
mongo.lua? this is 
local mongo = require 'mongo'
local client = mongo.Client(test.uri) ?? 

If you said that,I get on lua-mongo\1.2.1-1\doc

**Comment by GitHubProgarm** [comment]
i know what problem! mongo.lua is old file , my wrong

**Comment by neoxic** [comment]
I love this guy. It's not the first time he self-resolves his own issues.:-)
