### ISSUE TITLE
Installing 32 bit version lib?

### ISSUE THREAD

**Issue by sqpp** [neoxic/lua-mongo#19]
Hey, 

I am trying to use the lua-mongo, although getting the following error:

``LUA ERROR: error loading module 'mongo' from file '/usr/local/lib/lua/5.1/mongo.so':
	/usr/local/lib/lua/5.1/mongo.so: wrong ELF class: ELFCLASS64``

As far as I googled it, it seems that my version is 64 bit, but I am trying to run it on a 32 bit program, right?

At least the program where I am using (CS2D) is 32 Bit (and LUA 5.1)

**Comment by neoxic** [comment]
Hi,
Yes, you are right. It seems like your `mongo.so` was built as a 32-bit object. There are usually a couple of options  for you to consider depending on how you build lua-mongo.

If you use LuaRocks for building, I'm not sure it is multilib aware on its own, so you will have to use a 32-bit chrooted environment within your system with all the needed 32-bit packages. But who knows, maybe LuaRocks can handle this for you with some tweaking.

If you use CMake and your system is multilib (32/64-bit), just make it use the correct Lua instance via the `PKG_CONFIG_PATH` variable and add `-D MONGOC_LIBRARY_DIRS=/path/to/lib -D CMAKE_C_FLAGS=-m32` to help it find the correct mongo-c-driver library and force a 32-bit build.

**Comment by sqpp** [comment]
Yes, my system is indeed multilib.

Not sure where can I edit the PKG_CONFIG_PATH variable. 

The way I have made the build was: ``cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF .``
I haven't really added the library path, not sure where that would be in my case and which way, I also should use the command, as I have tried adding the CMAKE_C_FLAGS=-m32 but it simply returned this: ``cmake -D USE_LUA_VERSION=5.1 CMAKE_C_FLAGS=-m32 .`` 

Now I have got a build, but unsure if that would be the correct build path for the 32 bit version.
/usr/local/lib/lua/5.1/mongo.so

or maybe I have used the wrong parameters to build?

**Comment by neoxic** [comment]
Not sure what you are trying to build here - lua-mongo, mongo-c-driver or both. I thought you were talking about lua-mongo only. Refer to mongo-c-driver's documentation on how to install it properly.

As for 32-bit lua-mongo, build with CMake:
```
$ cmake -D USE_LUA_VERSION=5.1 -D CMAKE_C_FLAGS=-m32 .
$ make
```
Add your `PKG_CONFIG_PATH` if the above commands fail to link with the correct Lua library:
```
$ PKG_CONFIG_PATH="/usr/local/lib32/pkgconfig" cmake -D USE_LUA_VERSION=5.1 -D CMAKE_C_FLAGS=-m32 .
$ make
```
Give it a try by simply loading the module:
```
$ lua5.1 -l mongo
```
... or whatever is suitable for your system.

**Comment by sqpp** [comment]
I have decided to instead get a 32 bit Ubuntu, because it's a hassle to know where the 32 bit Lua Library installed for x86.

**Comment by sqpp** [comment]
@neoxic I get the following error upon trying to make the build.

Libbson is already built, so it should be all right. 

![image](https://user-images.githubusercontent.com/27697736/69240986-fec02e00-0b9d-11ea-939a-2a6957d749b2.png)

**Comment by neoxic** [comment]
You don't need `sudo` for building lua-mongo.

Looks like a mongoc's related issue on your particular system. Please refer to their user's manual for more details or file a report with them.

As a side note, since you are on a 32-bit system already, try first installing mongoc as a package (if available on your system) and build lua-mongo normally with LuaRocks.

I'm closing this for now...
