### ISSUE TITLE
i have question.How to limit bro.

### ISSUE THREAD

**Issue by tomanupong** [neoxic/lua-mongo#20]
how to limit guy. thank you.
```
#!/usr/bin/env lua
local mongo = require 'mongo'
local client = mongo.Client('mongodb://127.0.0.1')
local collection = client:getCollection('db', 'test_col')

for person in collection:find({},{sort = {age = -1}}):iterator() do
    print(person.name)
end
```

**Comment by tomanupong** [comment]
i try .
for person in collection:find({},{sort = {age = -1}}).limit(50):iterator() do
    print(person.name)
end
not work.Could you tell me another code.

**Comment by neoxic** [comment]
lua-mongo has nothing to do with Mongo Shell's syntax.

Use `skip` and/or `limit` options:
```Lua
local cursor = collection:find({}, {skip = 123, limit = 456})
```

**Comment by tomanupong** [comment]
thank you very much @neoxic

**Comment by tomanupong** [comment]
thank you so much guy.

**Comment by tomanupong** [comment]
thank you so much guy. @neoxic
