### ISSUE TITLE
how to use "{allowDiskUse: true }" in aggregate guy ?

### ISSUE THREAD

**Issue by tomanupong** [neoxic/lua-mongo#21]
i have more document more than 1000000 . cannot use allowDiskUse. 

```
for data_output in collection2:aggregate('[{"$group" : { "_id": "$num", "count": { "$sum": 1 } } },{"$match": {"_id" :{ "$ne" : null } , "count" : {"$gt": 1} } }, {"$project": {"num" : "$_id", "_id" : "$count"} },{"$sort":{"_id":-1}}],{"allowDiskUse": true}'):iterator() do
    print(data_output)
   return 0
end
```
error = Each element of the 'pipeline' array must be an object

thank you neoxic.

**Comment by neoxic** [comment]
I encourage you to read MongoDB's documentation. I guess I will need to implement issue templates to discourage questions unrelated to this project.
