### ISSUE TITLE
i cann't query.have problem.

### ISSUE THREAD

**Issue by tomanupong** [neoxic/lua-mongo#24]
Hi neoxic. I ahve problem.Iwant query this .
mongo shell i want.
`db.test.find({"$and":[{"num":{"$exists":true}},{"num":{"$nin":[0]}}]}).sort({num:1}).limit(1)`
i try query in 
`local query_max = mongo.BSON('{"$and":[{"num":{"$exists":true}},{"num":{"$nin":[0]}}]},{"limit":5}')
`
```
for select_data in collection:find(query_max):iterator() do
            print(select_data.num)
  end
```
respon =  {}
help pls neoxic.I think syntax me error.but i don't know guy.
thank you.

**Comment by neoxic** [comment]
Have you checked the README and the Reference? Have you looked at the tests as an example? Because your syntax is incorrect.

**Comment by tomanupong** [comment]
sorry. code this example guy.
collections test is for example .
i read README. i just want use $and in mongo.BSON .

**Comment by tomanupong** [comment]
thank you neoxic. i got it. 
Sorry i'm wrong. 
`{"$and":[{"num":{"$exists":true}}]}`
