### ISSUE TITLE
Requiring the library from Lua results in error ("undefined symbol: lua_tointeger")

### ISSUE THREAD

**Issue by Semphriss** [neoxic/lua-mongo#27]
Title is pretty much self-explanatory; the line ``local mongo = require 'mongo'`` will result in a crash saying the following :
```
lua: error loading module 'mongo' from file '/usr/local/lib/lua/5.2/mongo.so':
	/usr/local/lib/lua/5.2/mongo.so: undefined symbol: lua_tointeger
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	test/test-mongo.lua:1: in main chunk
	[C]: in ?
```
It does that on the test files given in the ``test/`` folder, as well as a dummy lua script with only the faulty line in it.

I'm running Ubuntu 19.10 and I'm using Lua 5.2. I compiled the driver with CMake.

Note : the compiler gave me some trouble (I had to specify that I was using Lua 5.2, and it said : ``-- Using Lua '5.2', version 5.1.5``), not sure if it's related.

Thanks in advance!

**Comment by neoxic** [comment]
> Note : the compiler gave me some trouble (I had to specify that I was using Lua 5.2, and it said : -- Using Lua '5.2', version 5.1.5), not sure if it's related.

This is probably related. Your `mongo.so` is probably built against Lua 5.1 and not Lua 5.2. You can check this by issuing a command:
```
ldd /usr/local/lib/lua/5.2/mongo.so
```
Also, why use CMake? Try installing via LuaRocks.

**Comment by Semphriss** [comment]
I'm not sure which library is Lua, so here's the whole output : 
```
	linux-vdso.so.1 (0x00007ffe94eee000)
	libmongoc-1.0.so.0 => /usr/local/lib/libmongoc-1.0.so.0 (0x00007f3576947000)
	libbson-1.0.so.0 => /usr/local/lib/libbson-1.0.so.0 (0x00007f3576908000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3576717000)
	libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f35766fa000)
	libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f3576668000)
	libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f3576393000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3576386000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f357636b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3576348000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3576a2d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3576342000)
```
I tried building with LuaRocks, but it couldn't detect libbson : 
```
$ sudo luarocks make
[sudo] password for user: 

Error: Could not find library file for LIBBSON
  No file bson-1.0 in /usr/local/lib
  No file bson-1.0 in /usr/local/lib/x86_64-linux-gnu
  No file bson-1.0 in /usr/lib
  No file bson-1.0 in /usr/lib/x86_64-linux-gnu
You may have to install LIBBSON in your system and/or pass LIBBSON_DIR or LIBBSON_LIBDIR to the luarocks command.
Example: luarocks install lua-mongo LIBBSON_DIR=/usr/local
```
Libbson was installed as a dependency when I installed the Mongo C Driver, but I can't seem to find any file names "bson-1.0" anywhere in any related folder.


----------


Now that I notice it, it says "libbson-**1.0**.so.0" and the dependency asks for 1.16+. Am I looking at the correct place for the version number?

**Comment by Semphriss** [comment]
Alright, I think I got it :
```
$ apt-cache show libbson-1.0
Package: libbson-1.0-0
Architecture: amd64
Version: 1.15.0-1
Priority: optional
Section: universe/libs
Source: mongo-c-driver
Origin: Ubuntu
```
"Version: **1.15.0-1**", literally one below.

Do you know where I can find an up-to-date version of libbson? The Mongo C Driver site only tells me to download it from apt...

**Comment by neoxic** [comment]
Wait, let’s leave libbson alone for now. 1.15 should be good.

Try running LuaRocks with the correct variables that it’s asking for:

    luarocks install lua-mongo LIBBSON_DIR=/usr/lib/bson-1.0 LIBMONGOC_DIR=/usr/lib/mongoc-1.0

...or whatever path is relevant in your case. Note that LuaRocks doesn’t track dependencies installed in your system that is why external dependencies must be specified explicitly. It’s normal.

**Comment by Semphriss** [comment]
I've played a bit with the paths and found that both are in /usr/local.

Now I get a compilation error :
```
$ sudo luarocks install lua-mongo LIBBSON_DIR=/usr/local/ LIBMONGOC_DIR=/usr/local/
Installing https://luarocks.org/lua-mongo-1.2.1-1.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.2 -c src/bson.c -o src/bson.o -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0
In file included from src/bson.c:23:
src/common.h:25:10: fatal error: lauxlib.h: No such file or directory
   25 | #include <lauxlib.h>
      |          ^~~~~~~~~~~
compilation terminated.

Error: Build error: Failed compiling object src/bson.o
```
Any ideas?

**Comment by neoxic** [comment]
Is there lauxlib.h in /usr/include/lua5.2 ?

**Comment by Semphriss** [comment]
I think I found something...

``/usr/include/lua5.1/lauxlib.h``

Yes, Lua 5.**1**... No idea why, because running ``lua5.2`` works, but running ``Lua5.1`` only prompts me to install it through apt.

I manually renamed the folder to lua5.2 (I know I shouldn't do this but I'm investigating) and it compiled properly.

I'll keep following the installation steps and I'll come back with news ASAP. Thanks for putting me on the right road!

**Comment by neoxic** [comment]
Yes, it looks more and more that you have Lua 5.1 vs 5.2 messed up in the system. You need to untangle that first. Otherwise, things will go wonky.

**Comment by neoxic** [comment]
It also could be that you have Lua 5.1 headers installed but not for Lua 5.2. Try installing a lua5.2-devel package or whatever is relevant for your system. Note that you always need Lua headers to build modules written in C.

**Comment by Semphriss** [comment]
It seems to work!

I did ``sudo apt-get install lua5.2-dev``, recompiled the module with LuaRocks, and the test script isn't printing any error anymore!

I'll try editing a collection to see if it really works :)

**Comment by Semphriss** [comment]
It works!

Thanks so much for your help!

**Comment by neoxic** [comment]
Great! I’m closing this then....
