### ISSUE TITLE
undefined symbol: mongoc_collection_replace_one

### ISSUE THREAD

**Issue by sergeydi** [neoxic/lua-mongo#31]
error during loading module:

```
[error] 12528#12528: *4392626 lua entry thread aborted: runtime error: error loading module 'mongo' from file '/usr/local/openresty/lualib/mongo.so':
        /usr/local/openresty/lualib/mongo.so: undefined symbol: mongoc_collection_replace_one
```

**Comment by neoxic** [comment]
Before opening a new issue, it's good practice to first check already closed issues if there's been a similar problem resolved.

Have you tried searching by "undefined symbol", for example?😊

**Comment by sergeydi** [comment]
You mean it is the same issue: https://github.com/neoxic/lua-mongo/issues/3 ?

**Comment by neoxic** [comment]
Your mongo.so is linked with the wrong libmongoc-1.0.so. Check similar closed issues for more hints.

**Comment by sergeydi** [comment]
Thank you.
