### ISSUE TITLE
i have problem guy.how to find or aggregation ISODate. 

### ISSUE THREAD

**Issue by tomanupong** [neoxic/lua-mongo#32]
i try. 
in mongo db
`{"start_time" : ISODate("2020-09-18T17:57:20Z"),"exp_time" : ISODate("2021-09-07T17:57:20Z")}`
how to find or aggregation time with gte or lte
i use query in mongo shell it work .
`db.collection.find({ "start_time" : { "$lte": ISODate("2020-09-18T17:57:20Z")} })`

how to find isodate in your lib 

thank you.

**Comment by neoxic** [comment]
Sorry, I have no idea what you are trying to tell me.
