### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by janosNH** [neoxic/lua-mongo#33]
In file collections.c at line 125:
int i, n = lua_gettop(L) - 1;
bson_t const *documents[n];

the [n] causes Error	C2057	expected constant expression	lua-mongo	C:\work\lua-mongo\src\collection.c	125	
with Visual Studio 2019. msvc does not support VLA, which is C99.

**Comment by neoxic** [comment]
Yes, this piece needs to be refactored. Thanks!

**Comment by neoxic** [comment]
For now, I think, you could simply assume a fixed length, say, 100. I'll do the same with throwing an error if `n > 100`.
