### ISSUE TITLE
nginx content_by_lua_block gives an error if ssl is used

### ISSUE THREAD

**Issue by aivils** [neoxic/lua-mongo#34]
If I use this package stand alone under lua or luajit everthing works fine.
If I use code under nginx
```
content_by_lua_block {           
             local mongo = require 'mongo'
             ...
}
```
the it gives an error
2020/10/09 08:06:23 [error] 1421#0: *51 lua entry thread aborted: runtime error: content_by_lua(nginx-kong.conf:283):24: No suitable servers found (`serverSelectionTryOnce` set): [TLS handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed calling ismaster on 'cluster0-shard-00-00.6h6bl.mongodb.net:27017'] [TLS handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed calling ismaster on 'cluster0-shard-00-01.6h6bl.mongodb.net:27017'] [TLS handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate

No error if SSL is not used. Plain mongodb://foo works fine.

**Comment by neoxic** [comment]
Although I believe this is unrelated to lua-mongo itself, I'll venture to throw an idea that probably TLS initialization in mongo-c-driver conflicts with the one in Nginx. Moreover, you haven't provided a code snippet, so one is left to guess. You could try to use different TLS backends in Nginx and mongo-c-driver to eliminate possible interference.

As a sidenote, using lua-mongo with OpenResty (I believe it's your case) defies the whole purpose of using asynchronous I/O in Nginx because mongo-c-driver is inherently synchronous, hence it will not use Nginx's I/O infrastructure and will always block the workers.

**Comment by aivils** [comment]
Later I realized that this site is right to report an error.
https://github.com/openresty/lua-nginx-module/issues/1801
Yes is kong's issue. kong provide different ssl library:

```
bash-5.0# ldd /usr/lib/libmongoc-1.0.so
        /lib/ld-musl-x86_64.so.1 (0x7f8ed61d3000)
        libssl.so.1.1 => /lib/libssl.so.1.1 (0x7f8ed60bb000)
        libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7f8ed5e3c000)
        libsnappy.so.1 => /usr/lib/libsnappy.so.1 (0x7f8ed5e30000)
        libz.so.1 => /lib/libz.so.1 (0x7f8ed5e16000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x7f8ed5d62000)
        libbson-1.0.so.0 => /usr/lib/libbson-1.0.so.0 (0x7f8ed5d22000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f8ed61d3000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f8ed5b89000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f8ed5b75000)
bash-5.0# 
bash-5.0# ldd /usr/local/openresty/nginx/sbin/nginx
        /lib/ld-musl-x86_64.so.1 (0x7f1b00765000)
        libluajit-5.1.so.2 => /usr/local/openresty/luajit/lib/libluajit-5.1.so.2 (0x7f1b0049b000)
        libssl.so.1.1 => /usr/local/kong/lib/libssl.so.1.1 (0x7f1b00407000)
        libcrypto.so.1.1 => /usr/local/kong/lib/libcrypto.so.1.1 (0x7f1b00121000)
        libz.so.1 => /lib/libz.so.1 (0x7f1b00107000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f1b00765000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f1b000f3000)
bash-5.0# 
```

Do you recommend recompiling mongoc with the libraries that come with openresty-kong?

**Comment by neoxic** [comment]
I'm not sure that having the same library as a dependency guarantees proper initialization both in Nginx and mongo-c-driver. OpenSSL is notorious to be user unfriendly as much as possible. It could work though, who knows. However, if this path fails, you could try building Nginx against another TLS library (MbedTLS for example) and leave mongo-c-driver suffering with OpenSSL or vice versa.
