### ISSUE TITLE
Process aborts due to a zero server_id

### ISSUE THREAD

**Issue by mokhadri** [neoxic/lua-mongo#35]
Make sure that you actually have database `TestDatabase` with collection `TestCollection` which contains 101+ documents:

```Lua
local mongo = require 'mongo'
local client = mongo.Client('mongodb://127.0.0.1')
local cmd = {find = "TestCollection"}
local cursor = client:command("TestDatabase", cmd)
return type(cursor)
```

The process will abort due to failed assertion `BSON_ASSERT (server_id);` inside `mongoc_cluster_stream_for_server()` in `mongoc-cluster.c`: **mongoc_cluster_stream_for_server(): precondition failed: server_id**

This seems to happen only if the data of firstBatch isn't fully consumed:

```Lua
local count = 0
for _ in cursor:iterator() do
	count = count + 1
	if count == 102 then break end -- any value smaller than 102 will abort
end
return count
```

**lua-mongo:** v1.2.0
**mongo-c-driver:** v1.15.1

**Comment by neoxic** [comment]
This looks like an issue with Mongo C Driver itself to me since the triggered assertion is internal. I can also see that you use mongo-c-driver 1.15. Try to upgrade before reporting upstream.
