### ISSUE TITLE
Unable to install lua-mongo with luarocks

### ISSUE THREAD

**Issue by danwize** [neoxic/lua-mongo#37]
I'm getting an error when I try to install lua-mongo with luarocks.  
![image](https://user-images.githubusercontent.com/29284872/103939505-17184280-50e9-11eb-99e6-6510192570a1.png)

`Installing https://luarocks.org/lua-mongo-1.2.2-1.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.2 -c src/bson.c -o src/bson.o -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/libbson-1.0
In file included from src/bson.c:23:
src/common.h:25:10: fatal error: lauxlib.h: No such file or directory
 #include <lauxlib.h>
          ^~~~~~~~~~~
compilation terminated.
`

I installed the mongo-c driver version 1.17.3 following these steps:  
`$ wget https://github.com/mongodb/mongo-c-driver/releases/download/1.17.3/mongo-c-driver-1.17.3.tar.gz
$ tar xzf mongo-c-driver-1.17.3.tar.gz
$ cd mongo-c-driver-1.17.3
$ mkdir cmake-build
$ cd cmake-build
$ cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF ..
$ make
$ sudo make install`

**Comment by danwize** [comment]
I found someone else solved a similar problem.  I had to install liblua5.2-dev according to this: https://github.com/ers35/luastatic/issues/18

**Comment by neoxic** [comment]
You need Lua headers to install modules written in C via LuaRocks.
