### ISSUE TITLE
unable to make an index creation

### ISSUE THREAD

**Issue by FBRISSON** [neoxic/lua-mongo#4]
I would like to create an index for my database but the syntax 👍 :ensureIndex(.. seems to be not implemented.

**Comment by neoxic** [comment]
Index creation functions in Mongo C Driver are deprecated. See [mongoc_collection_create_index()] for example.

To create indexes on a MongoDB collection, your best bet is to execute the `createIndexes` command on a MongoDB server via `client:command()`. For example:

```
client:command [[
{
    createIndexes: <collection>,
    indexes: [
        {
            key: {
                <key-value_pair>,
                <key-value_pair>,
                ...
            },
            name: <index_name>,
            <option1>,
            <option2>,
            ...
        },
        { ... },
        { ... }
    ],
}
]]
```

See [createIndexes] for more information.

[mongoc_collection_create_index()]: http://mongoc.org/libmongoc/current/mongoc_collection_create_index.html

[createIndexes]: https://docs.mongodb.com/manual/reference/command/createIndexes/

**Comment by FBRISSON** [comment]
Thank for your prompt reply, I really appreciate
After 2 hours of digging I finally get it working in LUA and find the write syntax

```
nbclient=OP_FindClient("ClientName")
client=op_client[nbclient]  -- get the client among multiple ones
query = [[
	{
	    "createIndexes":"sites",
		"indexes" : [
			{
			"key" : {
				"name":1,
				"addr":1,
				"ville":1
				},
				"name":"idx"
			}
			]
	}
	]]
queryBSON = mongo.BSON(query)
ret = client:command("myDBname",queryBSON)
```
