### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by tukotech** [neoxic/lua-mongo#40]
I tried luarocks + vcpkg but I can't get it to work. 

This is how I call it:
```
luarocks install lua-mongo LIBBSON_INCDIR=C:\g\vcpkg\packages\libbson_x86-windows LIBMONGOC_INCDIR=C:\g\vcpkg\packages\mongo-c-driver_x86-windows
```
output below
```
src/collection.c(125): error C2057: expected constant expression
src/collection.c(125): error C2466: cannot allocate an array of constant size 0
src/collection.c(125): error C2133: 'documents': unknown size

Error: Build error: Failed compiling object src/collection.obj
```

**Comment by tukotech** [comment]
Note: I tried to pull the latest and run it like:
```
luarocks install C:\g\lua-mongo\rockspec\lua-mongo-git-1.rockspec LIBBSON_INCDIR=C:\g\vcpkg\packages\libbson_x86-windows LIBMONGOC_INCDIR=C:\g\vcpkg\packages\mongo-c-driver_x86-windows
```

... but it fails with:
```
Error: Could not find expected file bson-1.0 for LIBBSON -- you may have to install LIBBSON in your system and/or set the LIBBSON_DIR variable
```

Which is unusual since it can be found using the rocks repo, see above.

**Comment by neoxic** [comment]
Well, your issues are LuaRocks-related.

FYI, I just made a new release (long overdue), so please try the usual way.

**Comment by tukotech** [comment]
The updated version looks very promising, I was able to build mongo.dll! Unfortunately it is not loading. Upon closer investigation it seems like my Lua version was compiled using MSVC++ 2005 (Msvcr80.dll) and I was building lua-mongo using MSVC++ 2019.

I will explore installing MSVC++2005 and see how it works.

Thanks for the library @neoxic
