### ISSUE TITLE
How to create a TTL index?

### ISSUE THREAD

**Issue by heetu** [neoxic/lua-mongo#42]
Can I create a TTL index with a lua-mango package?
If it is possible can you please me how in sort?

This is one of the excellent tools that I found for lua mongo connectivity.

I really appreciate any help you can provide.

**Comment by neoxic** [comment]
Of course, you can! You just need to figure out the underlying JSON format of the TTL index creation request and send it to a MongoDB server via the `client:command()` method.

**Comment by heetu** [comment]
Greate, Can you please share me small example if possible.

This is a shell command for creating an index.
`db.log_events.createIndex( { "expireAt": 1 }, { expireAfterSeconds: 0 } )`

I really appreciate any help you can provide.

**Comment by neoxic** [comment]
https://docs.mongodb.com/manual/reference/command/createIndexes/#mongodb-dbcommand-dbcmd.createIndexes

This is not a good place to ask MongoDB-related questions. Closing...

**Comment by heetu** [comment]
Really apologies for my silly question, but I think now I can solve my issues from this link.

Thank you so much for your attention and participation.
