### ISSUE TITLE
 Lua-mongo can't be used with mongo-c-driver_v1.19

### ISSUE THREAD

**Issue by 3244194454** [neoxic/lua-mongo#43]
![image](https://user-images.githubusercontent.com/34533389/141712063-e9bd6b4b-a1fa-4a85-aa6d-d60851e3c5cc.png)

code:
```
local client = mongo.Client(...)
local coll = client:getCollection("team", "mytest")
coll:insert('{ "name" : "Bobby", "age" : 23 }')
```
The code running environment is OpenResty  .

error:
*** Error in `nginx: worker process': free(): invalid next size (fast): 0x0000000002135360 ***
2021/11/14 20:38:06 [alert] 91383#91383: worker process 51751 exited on signal 11

**Comment by neoxic** [comment]
I don't see any problems running tests with mongo-c-driver 1.19 on all supported Lua versions. For example:
```
$ ctest
Test project /home/seny/build/lua-mongo/5.4
    Start 1: test-bson.lua
1/3 Test #1: test-bson.lua ....................   Passed    0.01 sec
    Start 2: test-gridfs.lua
2/3 Test #2: test-gridfs.lua ..................   Passed    0.09 sec
    Start 3: test-mongo.lua
3/3 Test #3: test-mongo.lua ...................   Passed    0.14 sec
```

```
$ pacman -Q mongo-c-driver
mongo-c-driver 1.19.0-1
$ mongod --version | head -n1
db version v5.0.3
```

EDIT: I had to fix the test a bit, but it's largely irrelevant to your issue.

**Comment by 3244194454** [comment]
Thanks !  It may be  caused by the Lua version of OpenResty. There were no problems with the tests under version mongo-c-driver 1.16 .  I will try again with the mongo-c-driver 1.16 . Thanks again !
