### ISSUE TITLE
building with luarocks mingw64

### ISSUE THREAD

**Issue by saspivey98** [neoxic/lua-mongo#45]
I downloaded the mongo-c-driver 1.16 binaries and built it using mingw64 MSYS Makefiles and gcc 12.2.1 on windows 10, 64-bit.

run this command in luarocks 3.3.1: 
```lua
luarocks install lua-mongo LIBBSON_DIR=C:\lua LIBMONGOC_DIR=C:\lua
```

this what is returned:

```cmd
Installing https://luarocks.org/lua-mongo-1.2.3-1.src.rock

lua-mongo 1.2.3-1 depends on lua >= 5.1 (5.3-1 provided by VM)
gcc -O2 -c -o src/bson.o -IC:\lua\include src/bson.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/bsontype.o -IC:\lua\include src/bsontype.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/bulkoperation.o -IC:\lua\include src/bulkoperation.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/client.o -IC:\lua\include src/client.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/collection.o -IC:\lua\include src/collection.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/cursor.o -IC:\lua\include src/cursor.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/database.o -IC:\lua\include src/database.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/flags.o -IC:\lua\include src/flags.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/gridfs.o -IC:\lua\include src/gridfs.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/gridfsfile.o -IC:\lua\include src/gridfsfile.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/gridfsfilelist.o -IC:\lua\include src/gridfsfilelist.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/main.o -IC:\lua\include src/main.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/objectid.o -IC:\lua\include src/objectid.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/readprefs.o -IC:\lua\include src/readprefs.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -O2 -c -o src/util.o -IC:\lua\include src/util.c -IC:\lua/include/libmongoc-1.0 -IC:\lua/include/libbson-1.0
gcc -shared -o mongo.dll src/bson.o src/bsontype.o src/bulkoperation.o src/client.o src/collection.o src/cursor.o src/database.o src/flags.o src/gridfs.o src/gridfsfile.o src/gridfsfilelist.o src/main.o src/objectid.o src/readprefs.o src/util.o -LC:\lua -LC:\lua -lmongoc-1.0 -lbson-1.0 C:\lua\lib/lua53.dll -lm
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmongoc-1.0: No such file or directory
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lbson-1.0: No such file or directory
collect2.exe: error: ld returned 1 exit status

Error: Build error: Failed compiling module mongo.dll
```

I genuinely don't know what -lmongoc-1.0 and -lbson-1.0 dependencies are referencing. 
Sorry if this is not the right place, I realize this is more a luarocks question.

**Comment by neoxic** [comment]
> I genuinely don't know what -lmongoc-1.0 and -lbson-1.0 dependencies are referencing.

They are referencing two libraries `libbson-1.0.lib` and `mongoc-1.0.lib` that are two parts of the Mongo-C-Driver and should be located in `c:\lua\lib` in your case.  If your compiler can't find them, the build will fail.

**Comment by saspivey98** [comment]
Interesting. I have those file names with `.dll` and `.dll.a` extensions in the `\lua\lib\` folder. It is problem with how the driver was built?

**Comment by neoxic** [comment]
I'm not a Windows guy, but as far as I can see, the Microsoft C compiler can't link against .dll, it needs an "export" part of a DLL-library in the form of a .lib file for linkage.

**Comment by saspivey98** [comment]
okay, so I think I figured it out. 

In the .rockspec:

```lua
external_dependencies = {
	LIBMONGOC = {
		header = 'libmongoc-1.0/mongoc/mongoc.h',
		library = 'mongoc-1.0'
	},
	LIBBSON = {
		header = 'libbson-1.0/bson/bson.h',
		library = 'bson-1.0'
	},
}
```
I added the library variables under each dependency, luarocks found the necessary linking files. No .lib files required.

**Comment by neoxic** [comment]
Hmm, interesting.... This is how it should have looked. I just checked that the rockspec in the repo looks exactly like this, but the one on LuaRocks was missing the libs. I guess I forgot to update the one on LuaRocks.org. Fixed that! Could you please attempt to install from LuaRocks again to confirm that it works for you? Thanks!

**Comment by neoxic** [comment]
I'm not sure what exactly changes for LuaRocks though, since the compiler was essentially looking for the same libs, i.e. `-lmongoc-1.0 and -lbson-1.0`. My guess is that when a non-standard location was used, LuaRocks would skip its own attempt to find the libs, thus not providing an additional library path to the compiler.

**Comment by saspivey98** [comment]
Yes, the new luarocks rockspec installs flawlessly now. I'm not totally certain why it needs the library property. Its definitely something to do with the path. Before the including the property, it was looking around cluelessly in the mingw64 folder. Even pointing luarocks to where it should be looking, it was still confused. 

The installation works, but the actual .dll file built isn't working when I require it with the lua interpreter. But, that's a different issue. I'll close this one :)
