### ISSUE TITLE
Support for Multi-field Sorting in find Method

### ISSUE THREAD

**Issue by Alan-MQ** [neoxic/lua-mongo#47]
Please note that **lua-mongo** is merely a binding to Mongo C Driver. It neither adds nor subtracts anything within the supported API.

Before reporting an issue, please make sure the problem is with **lua-mongo** itself rather than with MongoDB syntax or the Mongo C Driver API by checking the following links:

[MongoDB operators](https://docs.mongodb.com/manual/reference/operator/)

[Mongo C Driver API](http://mongoc.org/libmongoc/current/api.html)

Issues unrelated to **lua-mongo** will be closed without a warning.

---

**Title:** Support for Multi-field Sorting in `find` Method

**Description:**

Hi,

First of all, thank you for your great work on this library. I really appreciate it!

I have a question regarding the usage of the `find` method with multi-field sorting. In the README documentation, I found an example like this:

```lua
collection:find('{ "_id" : { "$gt" : 123 } }', {sort = {_id = -1}}):iterator()
```

However, in my practice, I want to use something like:

```lua
{sort = {field1 = -1, field2 = -1}}
```

This means I want to sort by `field1` in descending order as the first order and by `field2` in descending order as the second order. 

When I use it like this, there is no error in running the code, but the order returned from the `find` method doesn't seem to apply these sort rules.

Does this library support usage like this? If not, could you please consider adding support for multi-field sorting in the `find` method? Please let me know if there is anything I can help.

Thank you!

---

**Comment by Alan-MQ** [comment]
<img width="1701" alt="image" src="https://github.com/neoxic/lua-mongo/assets/109934126/607be82d-a3cb-445e-a647-5e573e22696a">
I've checked the mongodb c drive and maybe we should use order by for this one ?

**Comment by neoxic** [comment]
As mentioned above, lua-mongo is merely a binding to Mongo C Driver. It neither adds nor subtracts anything within the supported API. Your best bet is to first check if your queries work as expected in the Mongo Shell.

**Comment by Alan-MQ** [comment]
> As mentioned above, lua-mongo is merely a binding to Mongo C Driver. It neither adds nor subtracts anything within the supported API. Your best bet is to first check if your queries work as expected in the Mongo Shell.

Thank you for your reply. As mentioned above, lua-mongo is merely a binding to the Mongo C Driver. It neither adds nor subtracts anything within the supported API.（noted~~）

I've checked the query in MongoDB Shell, and it works fine. For example:

```javascript
db.team_battle_info.find({BattleID: "xxx"}).sort({"Camp": -1, "Exp": -1})
```

However, when I use a similar query in Lua like this:

```lua
for team in col:find(query, {sort = {Camp = -1, TeamId = -1}}):iterator() do
```

The order is not stable. I was wondering if the issue might be related to the second parameter `{sort = {Camp = -1, TeamId = -1}}` being a table. There might be some problem with turning the options into the Mongo C driver.

I hope I made myself clear. Please let me know if there is anything unclear or if you need more information.

Thank you!

**Comment by neoxic** [comment]
The problem with Lua tables is that there is no specific order in which non-numeric keys are iterated. The table `{Camp = -1, TeamId = -1}` can become either `{"Camp":-1,"TeamId":-1}` or `{"TeamId":-1,"Camp":-1}` upon conversion to BSON, and that's probably not what you want. Check this out:
https://github.com/neoxic/lua-mongo/blob/master/doc/main.md#mongobsonvalue

Try passing `options` as a JSON string, i.e. `'{"sort":{"Camp":-1,"TeamId":-1}}'`.

**Comment by Alan-MQ** [comment]
> The problem with Lua tables is that there is no specific order in which non-numeric keys are iterated. The table `{Camp = -1, TeamId = -1}` can become either `{"Camp":-1,"TeamId":-1}` or `{"TeamId":-1,"Camp":-1}` upon conversion to BSON, and that's probably not what you want. Check this out: https://github.com/neoxic/lua-mongo/blob/master/doc/main.md#mongobsonvalue
> 
> Try passing `options` as a JSON string, i.e. `'{"sort":{"Camp":-1,"TeamId":-1}}'`.

JSON string works just fine, thank you for this~~
