### ISSUE TITLE
the positional $ operator seems to be not suported

### ISSUE THREAD

**Issue by FBRISSON** [neoxic/lua-mongo#5]
We try to use the notation $ to select all the array value in the projection but this notation seems to be not implemented !
the string is : 
````
str=string.format([[
[
                { "$match": 
                               {
                                               "Code_IG":"6546544",
                                               "POS.freq":"474"
                               }
                } ,
                { "$projecti": 
                               { 
                                               "clientID":1,
                                               "POS.$":1,
                                               "_idques":0 
                               }
                }
]
]])query=mongo.BSON(str)
loop=collection:aggregate(query):value();
if loop then
OP_Display_mongo_list("document",loop);
End
```

**Comment by FBRISSON** [comment]
If I try with findOne it is the same issue

```
db.getCollection('sites').find(
{
"code_ig":141602,
"POS.frequence":658
},
{
"POS.frequence.$":1
}
)
```
if I remove the projection its works fine. POS is an array

**Comment by neoxic** [comment]
`lua-mongo` provides Lua API to Mongo C Driver which means that within the API it is merely a translator. In your case, if you are having issues with operators, command syntaxes, etc., please refer to the user's manual of **your** version of MongoDB C Driver and/or MongoDB server.

If there is evidence that the issue in on the side of `lua-mongo`, please provide a comprehensive bug report.

**Comment by FBRISSON** [comment]
I agree I am not an old expert on mongoDB. 
Here the description of what I am trying to do with LUA.

First i'll expose what I do with javascript command on robot3t

I create a very simple collection with 2 documents

```
db.getCollection('test').insert({
 name : "tb1",
 array : [
	{obj1: 50, obj2 : 80},
	{obj1: 30, obj2 : 60},
	{obj1: 20, obj2 : 10},
	{obj1: 2, obj2 : 1}
	]
})

db.getCollection('test').insert({
 name : "tb2",
 array : [
	{obj1: 50, obj2 : 80},
	{obj1: 30, obj2 : 60},
	{obj1: 20, obj2 : 10},
	{obj1: 2, obj2 : 1}
	]
})
```
 
next I do the following find on this collection, with a projection including the $ positionnal

`db.getCollection('test').find({name:"tb1","array.obj1":50},{"array.$":1})
`
I got this answer

```
{
    "_id" : ObjectId("5b3de9584f19d8c35e17602b"),
    "array" : [ 
        {
            "obj1" : 50.0,
            "obj2" : 80.0
        }
    ]
}

```

exactly what I want.

If I try to do something similar with lua

```
query = '{"name":"tb1","array.obj1":50},{"array.$":1})'
queryBSON = mongo.BSON(query)
field = sites:findOne(queryBSON):value()
```
I got the error : Got parse error at ")", position 44: "SPECIAL_EXPECTED"

is there a way to use this positional $ in LUA ?

**Comment by neoxic** [comment]
```Lua
query = '{"name":"tb1","array.obj1":50},{"array.$":1})'
                                                     ^
                            Position 44 is here  ----|
```

You are getting this parse error because your JSON is invalid. Additionally, this is not a valid MongoDB query as far as I can tell.

Please also note that **lua-mongo**'s API does NOT match **MongoDB-shell**'s syntax. All similarities are accidental. So it is an error to expect this:
```Lua
collection:findOne(query, [options], [prefs])
```
to give the same result as the one of **MongoDB-shell**:
```JS
db.collection.findOne(query, projection)
```

To do what you want in Lua, use the `projection` option of the `find` query. For example:
```Lua
print(collection:findOne('{"name":"tb1", "array.obj1":50}', '{"projection":{"array.$":1}}'))
```

For more information, refer to https://docs.mongodb.com/master/reference/command/find/

**Comment by neoxic** [comment]
As a side note, projection and the positional operator `$[]` are two unrelated things. The former is used in `find` queries and the latter is used in updates. I am not a MongoDB expert though, so feel free to research it on your own.
