### ISSUE TITLE
Trying to retrieve the server date with serverStatus

### ISSUE THREAD

**Issue by FBRISSON** [neoxic/lua-mongo#6]
I am unable to find the syntax that will give me the serverStatus and so the Date of the server.

I have tried something like 

ret = client:command("myDb",' { "serverStatus' : 1 } ' )
 but ret is not a document

In the database methods documentation  there is no database:serverStatus() as I would expect

Thanks a lot for any help

**Comment by neoxic** [comment]
```Lua
ret = client:command("myDb",' { "serverStatus' : 1 } ' )
                                             ^
                                             |- invalid JSON

```
Please stop posting reports with invalid JSON as already mentioned before! This is a waste of time for everybody.

Also, if you do report, please provide comprehensive information! "but ret is not a document" - what is one supposed to do with this? What exactly is the output, what is expected, according to what, etc.?

Next time, I will close underreported issues without a warning. Thank you!

**Comment by neoxic** [comment]
As it looks you are new to Lua, it is considered good practice in Lua to wrap calls that return errors in `assert()` to generate exception if you are not ready to handle errors manually. The use of local variables is also handy.

Instead of:
```Lua
local res, err = assert(client:command('myDb', 'INVALID JSON'))
if res then
    print(res)
else
    print('ERROR', err)
end
```
simply do:
```Lua
local res = assert(client:command('myDb', 'INVALID JSON'))
print(res)
```

**Comment by FBRISSON** [comment]
My apologize for this not well documented issues. I have mistyped the code when I wrote this issue. 
I am not so new to LUA but it is the case with the MongoDB LUA drivers that I  would like to use. I have mainly difficulties to find the proper syntax to use in the help pages attached to the driver. I use the term Document like in the MongoDB literature, collection contains document and so I want to retrieve document. You can close this issue and again sorry for your waste of time.

**Comment by neoxic** [comment]
Well, there is no issue on the part of `lua-mongo` as far as I am concerned:

```Lua
local res = assert(client:command('test-collection', '{"serverStatus":1}')):value()
print('UPTIME', res.uptime)
```
```
UPTIME (sec)	136
```

I believe you have issues from time to time because you misunderstand documentation and then produce code that doesn't show you your own mistakes.:-)
