### ISSUE TITLE
`mongo.BSON {a={1,2,3}}` segfaults

### ISSUE THREAD

**Issue by pbosetti** [neoxic/lua-mongo#7]
The following

    mongo.BSON {a={__array, 1, 2, 3}}

segfaults, as well as the syntax in title. At least, an error, rather than a segfault, shall be issued by Lua.

**Comment by neoxic** [comment]
Please see this issue #2 and report back. Thanks!

**Comment by neoxic** [comment]
No further feedback received. Closing as a duplicate of #2 ...
