### ISSUE TITLE
$sort operator

### ISSUE THREAD

**Issue by robitex** [neoxic/lua-mongo#9]
Hi all,
Is there a chance to have got the $sort operator for query option or as a cursor method?
For my understanding, your project doesn't support server side sorting. Does it?
Thank you.
R.

**Comment by neoxic** [comment]
Sorting is done via query options as per MongoDB's command syntax. Options are passed to `mongo-c-driver` as-is, so your best bet is to always refer to MongoDB's documentation first. See this for example:
```Lua
-- Iterate documents in a for-loop
local age_desc = mongo.BSON{sort = {age = -1}}
for person in collection:find({}, age_desc):iterator() do
    print(person.name, person.age)
end
```
